In [23]:
import numpy as np
from numpy.linalg import eig

## Pauli Matrices
파울리 행렬의 아이겐밸류와 아이겐벡터를 구하시오.

In [24]:
sx= np.matrix('0,1;1,0')
sy= np.matrix('0,-1j;1j,0')
sz= np.matrix('1,0;0,-1')
sx,sy,sz

(matrix([[0, 1],
         [1, 0]]),
 matrix([[ 0.+0.j, -0.-1.j],
         [ 0.+1.j,  0.+0.j]]),
 matrix([[ 1,  0],
         [ 0, -1]]))

In [32]:
eig(sx)[0], eig(sx)[1]

(array([ 1., -1.]),
 matrix([[ 0.70710678, -0.70710678],
         [ 0.70710678,  0.70710678]]))

In [29]:
eig(sy)[0], eig(sy)[1]

(array([ 1.+0.j, -1.+0.j]),
 matrix([[-0.        -0.70710678j,  0.70710678+0.j        ],
         [ 0.70710678+0.j        ,  0.        -0.70710678j]]))

In [30]:
eig(sz)[0], eig(sz)[1]

(array([ 1., -1.]),
 matrix([[1., 0.],
         [0., 1.]]))

## Normal Modes
### (고전역학 by Thornton & Marion 챕터 12.2 및 예제 12.3 참조) 용수철 상수가 $k$인 용수철에 연결된 두 개의 물체의 노말 모드를 구해보자. 두 개의 물체의 운동방정식은 다음으로 주어진다.<br>$$ -m w^2 x_1 = -2kx_1 +k x_2, \\
-m w^2 x_2 = k x_1 - 2 k x_2.$$ <br> eigenfrequencies $w$는 다음의 행렬식을 통해 구할 수 있다.

In [48]:
# 행렬 ([2,-1],[-1,2]) 의 고유값
M = np.matrix('2,-1;-1,2')
eig(M)

(array([3., 1.]),
 matrix([[ 0.70710678,  0.70710678],
         [-0.70710678,  0.70710678]]))

eigenvector $ V = \ \begin{pmatrix} 1/\sqrt{2} & 1/\sqrt{2}  \\ -1/\sqrt{2}  &1/\sqrt{2}  \end{pmatrix} = \begin{pmatrix} \cos-\pi/4 & -\sin-\pi/4  \\ \sin-\pi/4 & \cos-\pi/4 \end{pmatrix} $ 으로 -45도 만큼 돌리는 회전행렬과 같고,<br> D가 대각성분이 eigenvalue인 대각행렬 이라하면, $ M = VDV^{-1} $ 이므로<br> $MX=VDV^{-1}X$는 $x_1,x_2$를 45도 만큼 회전시킨 후, $x_1 \rightarrow 3x_1$, $x_2 \rightarrow x_2$ 만큼 바꾸고, 다시 -45도 만큼 회전 시키는 변환이다.